### ISSUE TITLE
Danh sách hiển thị tin tuyển dụng

### ISSUE THREAD

**Issue by nhanngo2511** [nguyenhuuluan/CapstoneProject_K20T_SHINES#1]
Danh sách hiển thị tin tuyển dụng nên sử dụng datatable đồng thời chỉ được sort và search các trường sau đây:

1. is_hot
2. number_of_view
3. status_id
4. company_name
5. created_at

Và mỗi bài đăng có 1 nút "XEM"

**Comment by thanhhuynhsg** [comment]
M pull về cái t làm hôm qua xem thử đi. phần BackPage đó

**Comment by nhanngo2511** [comment]
OK, đúng r đó, đại khái là v đi, sau này có chỉnh sửa gì nữa thì làm tiếp
