### ISSUE TITLE
Cập nhật trang update profile sinh viên

### ISSUE THREAD

**Issue by nguyenhuuluan** [nguyenhuuluan/CapstoneProject_K20T_SHINES#6]
Thêm giới tính, ngày sinh, hiển thị cv đã upload
Bỏ bớt bằng cấp
Chỉnh sửa thanh rating, datetime picker

**Comment by thanhhuynhsg** [comment]
done

**Comment by nguyenhuuluan** [comment]
![capture](https://user-images.githubusercontent.com/15241781/37291119-90d99ba4-2640-11e8-82ce-bccece35d2bb.PNG)

Chỉnh chỗ này lại cho đồng nhất khung nhập giống mấy cái sát bên giùm mình

**Comment by thanhhuynhsg** [comment]
done
